CREATE DATABASE SweetnSalty;


CREATE TABLE Person(
PersonID INT PRIMARY KEY IDENTITY,
FirstName nvarchar(30) NOT NULL,
LastName nvarchar(20) NOT NULL);

CREATE TABLE Flavor(
FlavorID INT PRIMARY KEY IDENTITY,
FlavorName nvarchar(50) NOT NULL);

CREATE TABLE PersonFlavorJunction
(
RowID INT PRIMARY KEY IDENTITY,
PersonID INT NOT NULL FOREIGN KEY REFERENCES Person(PersonID) ON DELETE CASCADE,
FlavorID INT NOT NULL FOREIGN KEY REFERENCES Flavor(FlavorID) ON DELETE CASCADE
);

